# Site
title: MHYC.eu.org
description: We will know, we must know.
url: https://mhyc.eu.org
logo: favicons/logo.png                                       # Site logo
locale: zh_CN

# Left Block Images
background:
  homepage: images/home.png                           # this image will be shown on homepage's left block
  post-list: images/home.png             # this image will be shown on post list page
  default-post: images/home.png   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
#google-analytics: UA-XXXXX-Y

# Social Links
email:             MHYC133@outlook.com
#google.plus:        username
#twitter:            username
#facebook:           username
github:             MHYCWasTaken
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username
discord:            MHYC133#2685
bilibili:           1251782597
# TODO discord and bilibili

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages, CNAME, robot.txt]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, Rakefile, .sass-cache, .DS_Store]
